<?php

declare(strict_types=1);

use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\CitiesReportController;
use App\Http\Controllers\ComparisonReportController;
use App\Http\Controllers\DashboardLabController;
use App\Http\Controllers\DamagesReportController;
use App\Http\Controllers\DeliveriesReportController;
use App\Http\Controllers\GovernoratesSettingsController;
use App\Http\Controllers\IdentifierController;
use App\Http\Controllers\InvoiceBrandingSettingsController;
use App\Http\Controllers\InvoicesReportController;
use App\Http\Controllers\NonWorkingHolidaysSettingsController;
use App\Http\Controllers\OperationsTasksController;
use App\Http\Controllers\ReportAssemblyController;
use App\Http\Controllers\ReportGuideController;
use App\Http\Controllers\ReportUsersController;
use App\Http\Controllers\SalesByItemAverageReportController;
use App\Http\Controllers\SalesByItemReportController;
use App\Http\Controllers\SalesBySalesmanReportController;
use App\Http\Controllers\SalesReportController;
use App\Http\Controllers\SchemaExplorerController;
use App\Http\Controllers\SqliteBackupSettingsController;
use App\Http\Controllers\StorageItemsReportController;
use App\Http\Controllers\StorageReportController;
use App\Http\Controllers\VisitsReportController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/login', [AdminAuthController::class, 'showLoginForm'])->name('login');
Route::post('/login', [AdminAuthController::class, 'login'])->name('login.attempt');
Route::post('/logout', [AdminAuthController::class, 'logout'])->name('logout');

Route::prefix('reports')->middleware(['reports.admin', 'reports.permission'])->group(function (): void {
    Route::get('/no-access', [AdminAuthController::class, 'noAccess'])->name('reports.no-access');
    Route::redirect('dashboard', 'dashboard-lab', 301);
    Route::redirect('dashboard/metrics', 'dashboard-lab/metrics', 301);
    Route::get('/dashboard-lab', [DashboardLabController::class, 'index'])->name('reports.dashboard-lab.index');
    Route::get('/dashboard-lab/metrics', [DashboardLabController::class, 'metrics'])->name('reports.dashboard-lab.metrics');
    Route::get('/sales', [SalesReportController::class, 'index'])->name('reports.sales.index');
    Route::get('/sales/client-items', [SalesReportController::class, 'clientItems'])->name('reports.sales.client-items');
    Route::get('/comparison', [ComparisonReportController::class, 'index'])->name('reports.comparison.index');
    Route::get('/comparison/export/pdf', [ComparisonReportController::class, 'exportPdf'])->name('reports.comparison.export.pdf');
    Route::get('/comparison/export/csv', [ComparisonReportController::class, 'exportCsv'])->name('reports.comparison.export.csv');
    Route::get('/sales/export/pdf', [SalesReportController::class, 'exportPdf'])->name('reports.sales.export.pdf');
    Route::get('/sales/export/csv', [SalesReportController::class, 'exportCsv'])->name('reports.sales.export.csv');
    Route::get('/sales-item-average', [SalesByItemAverageReportController::class, 'index'])->name('reports.sales-item-average.index');
    Route::get('/sales-item-average/items', [SalesByItemAverageReportController::class, 'categoryItems'])->name('reports.sales-item-average.items');
    Route::get('/sales-item-average/export/pdf', [SalesByItemAverageReportController::class, 'exportPdf'])->name('reports.sales-item-average.export.pdf');
    Route::get('/sales-item-average/export/csv', [SalesByItemAverageReportController::class, 'exportCsv'])->name('reports.sales-item-average.export.csv');
    Route::get('/sales-by-salesman', [SalesBySalesmanReportController::class, 'index'])->name('reports.sales-by-salesman.index');
    Route::get('/sales-by-salesman/export/pdf', [SalesBySalesmanReportController::class, 'exportPdf'])->name('reports.sales-by-salesman.export.pdf');
    Route::get('/sales-by-salesman/export/csv', [SalesBySalesmanReportController::class, 'exportCsv'])->name('reports.sales-by-salesman.export.csv');
    Route::get('/sales-by-item', [SalesByItemReportController::class, 'index'])->name('reports.sales-by-item.index');
    Route::get('/sales-by-item/export/pdf', [SalesByItemReportController::class, 'exportPdf'])->name('reports.sales-by-item.export.pdf');
    Route::get('/sales-by-item/export/csv', [SalesByItemReportController::class, 'exportCsv'])->name('reports.sales-by-item.export.csv');
    Route::get('/storage-items', [StorageItemsReportController::class, 'index'])->name('reports.storage-items.index');
    Route::get('/storage-items/evaluation', [StorageItemsReportController::class, 'evaluation'])->name('reports.storage-items.evaluation');
    Route::get('/storage-items/export/pdf', [StorageItemsReportController::class, 'exportPdf'])->name('reports.storage-items.export.pdf');
    Route::get('/storage-items/export/csv', [StorageItemsReportController::class, 'exportCsv'])->name('reports.storage-items.export.csv');
    Route::get('/storage', [StorageReportController::class, 'index'])->name('reports.storage.index');
    Route::get('/storage/export/pdf', [StorageReportController::class, 'exportPdf'])->name('reports.storage.export.pdf');
    Route::get('/storage/export/csv', [StorageReportController::class, 'exportCsv'])->name('reports.storage.export.csv');
    Route::get('/deliveries', [DeliveriesReportController::class, 'index'])->name('reports.deliveries.index');
    Route::post('/deliveries/setup/driver', [DeliveriesReportController::class, 'saveDriver'])->name('reports.deliveries.setup.driver');
    Route::put('/deliveries/setup/driver/{person}', [DeliveriesReportController::class, 'updateDriver'])->name('reports.deliveries.setup.driver.update');
    Route::delete('/deliveries/setup/driver/{person}', [DeliveriesReportController::class, 'deleteDriver'])->name('reports.deliveries.setup.driver.delete');
    Route::post('/deliveries/setup/companion', [DeliveriesReportController::class, 'saveCompanion'])->name('reports.deliveries.setup.companion');
    Route::put('/deliveries/setup/companion/{person}', [DeliveriesReportController::class, 'updateCompanion'])->name('reports.deliveries.setup.companion.update');
    Route::delete('/deliveries/setup/companion/{person}', [DeliveriesReportController::class, 'deleteCompanion'])->name('reports.deliveries.setup.companion.delete');
    Route::post('/deliveries/setup/daily-team', [DeliveriesReportController::class, 'saveDailyTeam'])->name('reports.deliveries.setup.daily-team');
    Route::delete('/deliveries/setup/daily-team/{team}', [DeliveriesReportController::class, 'deleteDailyTeam'])->name('reports.deliveries.setup.daily-team.delete');
    Route::post('/deliveries/status', [DeliveriesReportController::class, 'updateDeliveryStatus'])->name('reports.deliveries.status');
    Route::post('/deliveries/assign-team', [DeliveriesReportController::class, 'assignInvoiceTeam'])->name('reports.deliveries.assign-team');
    Route::post('/deliveries/batch-assign', [DeliveriesReportController::class, 'batchAssignFromPdf'])->name('reports.deliveries.batch-assign');
    Route::post('/deliveries/clear-team-assignments', [DeliveriesReportController::class, 'clearTeamAssignments'])->name('reports.deliveries.clear-team-assignments');
    Route::post('/deliveries/receipts/booklets', [DeliveriesReportController::class, 'storeReceiptBooklets'])->name('reports.deliveries.receipts.store');
    Route::post('/deliveries/receipts/assign', [DeliveriesReportController::class, 'assignReceiptBooklet'])->name('reports.deliveries.receipts.assign');
    Route::post('/deliveries/receipts/return', [DeliveriesReportController::class, 'returnReceiptBooklet'])->name('reports.deliveries.receipts.return');
    Route::get('/deliveries/export/pdf', [DeliveriesReportController::class, 'exportPdf'])->name('reports.deliveries.export.pdf');
    Route::get('/deliveries/export/csv', [DeliveriesReportController::class, 'exportCsv'])->name('reports.deliveries.export.csv');
    Route::get('/invoices', [InvoicesReportController::class, 'index'])->name('reports.invoices.index');
    Route::get('/invoices/items', [InvoicesReportController::class, 'items'])->name('reports.invoices.items');
    Route::post('/invoices/selection', [InvoicesReportController::class, 'updateSelection'])->name('reports.invoices.selection');
    Route::get('/invoices/print', [InvoicesReportController::class, 'printInvoice'])->name('reports.invoices.print');
    Route::get('/invoices/export/pdf', [InvoicesReportController::class, 'exportInvoicePdf'])->name('reports.invoices.export.pdf');
    Route::get('/invoices/export/list-csv', [InvoicesReportController::class, 'exportListCsv'])->name('reports.invoices.export.list-csv');
    Route::get('/invoices/export/list-pdf', [InvoicesReportController::class, 'exportListPdf'])->name('reports.invoices.export.list-pdf');
    Route::get('/invoice-branding', [InvoiceBrandingSettingsController::class, 'index'])->name('reports.invoice-branding.index');
    Route::post('/invoice-branding', [InvoiceBrandingSettingsController::class, 'save'])->name('reports.invoice-branding.save');
    Route::get('/holidays', [NonWorkingHolidaysSettingsController::class, 'index'])->name('reports.holidays.index');
    Route::post('/holidays', [NonWorkingHolidaysSettingsController::class, 'store'])->name('reports.holidays.store');
    Route::delete('/holidays/{holiday}', [NonWorkingHolidaysSettingsController::class, 'destroy'])->name('reports.holidays.destroy');
    Route::get('/report-assembly', [ReportAssemblyController::class, 'index'])->name('reports.report-assembly.index');
    Route::post('/report-assembly/categories', [ReportAssemblyController::class, 'saveCategories'])->name('reports.report-assembly.categories.save');
    Route::post('/report-assembly/items', [ReportAssemblyController::class, 'saveItems'])->name('reports.report-assembly.items.save');
    Route::get('/governorates', [GovernoratesSettingsController::class, 'index'])->name('reports.governorates.index');
    Route::post('/governorates', [GovernoratesSettingsController::class, 'store'])->name('reports.governorates.store');
    Route::get('/cities', [CitiesReportController::class, 'index'])->name('reports.cities.index');
    Route::get('/cities/export/pdf', [CitiesReportController::class, 'exportPdf'])->name('reports.cities.export.pdf');
    Route::get('/cities/export/chart-pdf', [CitiesReportController::class, 'exportChartPdf'])->name('reports.cities.export.chart-pdf');
    Route::get('/cities/export/csv', [CitiesReportController::class, 'exportCsv'])->name('reports.cities.export.csv');
    Route::get('/visits', [VisitsReportController::class, 'index'])->name('reports.visits.index');
    Route::get('/visits/export/pdf', [VisitsReportController::class, 'exportPdf'])->name('reports.visits.export.pdf');
    Route::get('/visits/export/csv', [VisitsReportController::class, 'exportCsv'])->name('reports.visits.export.csv');
    Route::get('/damages', [DamagesReportController::class, 'index'])->name('reports.damages.index');
    Route::post('/damages/packaging', [DamagesReportController::class, 'storePackaging'])->name('reports.damages.packaging.store');
    Route::post('/damages/packaging/delete', [DamagesReportController::class, 'deletePackaging'])->name('reports.damages.packaging.delete');
    Route::post('/damages/entries', [DamagesReportController::class, 'storeEntry'])->name('reports.damages.entries.store');
    Route::post('/damages/entries/delete', [DamagesReportController::class, 'deleteEntry'])->name('reports.damages.entries.delete');
    Route::get('/damages/api/items', [DamagesReportController::class, 'apiItems'])->name('reports.damages.api.items');
    Route::get('/damages/api/clients', [DamagesReportController::class, 'apiClients'])->name('reports.damages.api.clients');
    Route::get('/damages/export/pdf', [DamagesReportController::class, 'exportPdf'])->name('reports.damages.export.pdf');
    Route::get('/damages/export/csv', [DamagesReportController::class, 'exportCsv'])->name('reports.damages.export.csv');
    Route::get('/tasks', [OperationsTasksController::class, 'index'])->name('reports.tasks.index');
    Route::post('/tasks', [OperationsTasksController::class, 'store'])->name('reports.tasks.store');
    Route::put('/tasks/{task}', [OperationsTasksController::class, 'update'])->name('reports.tasks.update');
    Route::post('/tasks/{task}/complete', [OperationsTasksController::class, 'complete'])->name('reports.tasks.complete');
    Route::delete('/tasks/{task}', [OperationsTasksController::class, 'destroy'])->name('reports.tasks.destroy');
    Route::post('/tasks/due', [OperationsTasksController::class, 'dueNow'])->name('reports.tasks.due');
    Route::get('/schema', [SchemaExplorerController::class, 'index'])->name('reports.schema.index');
    Route::get('/guide', [ReportGuideController::class, 'index'])->name('reports.guide.index');
    Route::get('/identifier', [IdentifierController::class, 'index'])->name('reports.identifier.index');
    Route::get('/users', [ReportUsersController::class, 'index'])->name('reports.users.index');
    Route::post('/users', [ReportUsersController::class, 'store'])->name('reports.users.store');
    Route::put('/users/{user}', [ReportUsersController::class, 'update'])->name('reports.users.update');
    Route::delete('/users/{user}', [ReportUsersController::class, 'destroy'])->name('reports.users.destroy');
    Route::get('/sqlite-backups', [SqliteBackupSettingsController::class, 'index'])->name('reports.sqlite-backups.index');
    Route::post('/sqlite-backups/auto-settings', [SqliteBackupSettingsController::class, 'updateAutoBackup'])->name('reports.sqlite-backups.auto-settings');
    Route::post('/sqlite-backups/auto-run', [SqliteBackupSettingsController::class, 'runAutoBackupNow'])->name('reports.sqlite-backups.auto-run');
    Route::post('/sqlite-backups', [SqliteBackupSettingsController::class, 'store'])->name('reports.sqlite-backups.store');
    Route::get('/sqlite-backups/download/{filename}', [SqliteBackupSettingsController::class, 'download'])->name('reports.sqlite-backups.download');
    Route::post('/sqlite-backups/restore-upload', [SqliteBackupSettingsController::class, 'restoreUpload'])->name('reports.sqlite-backups.restore-upload');
    Route::post('/sqlite-backups/restore-stored', [SqliteBackupSettingsController::class, 'restoreStored'])->name('reports.sqlite-backups.restore-stored');
    Route::delete('/sqlite-backups/{filename}', [SqliteBackupSettingsController::class, 'destroy'])->name('reports.sqlite-backups.destroy');
});
